services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: "agent -dev -client=0.0.0.0"
    networks:
      - skillup

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ~/docker/mysql/data:/var/lib/mysql
      - ~/docker/mysql/sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - skillup

#  redis:
#    image: redis
#    container_name: redis
#    ports:
#      - 6379:6379
#    restart: always
#    networks:
#      - skillup

  rmqnamesrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    environment:
      JAVA_OPT_EXT: "-server -Xms1g -Xmx1g"
    volumes:
      - ~/docker/rocketmq/nameserver/logs:/root/logs
    command: sh mqnamesrv
    restart: always
    networks:
      skillup:
        aliases:
          - rmqnamesrv

  rmqbroker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    restart: always
    depends_on:
      - rmqnamesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ~/docker/rocketmq/broker/logs:/root/logs
      - ~/docker/rocketmq/broker/store:/root/store
      - ~/docker/rocketmq/broker/conf/broker.conf:/opt/rocketmq/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPT_EXT: "-server -Xms1g -Xmx1g -Xmn1g"
    networks:
      skillup:
        aliases:
          - rmqbroker

  rmqconsole:
    image: candice0630/rocketmq-console-ng:2.0 # arm 版本
    container_name: rocketmq-console
    restart: always
    ports:
      - 19876:8080
    depends_on:
      - rmqnamesrv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/rocketmq/console/logs:/root/logs
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      skillup:
        aliases:
          - rmqconsole

networks:
  skillup:
    name: skillup_net
    driver: bridge
    external: true
