server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillup
    username: root
    password: 672546
  flyway:
    baseline-on-migrate: true
    enabled: true

# Custom Config
promotion:
  stock-strategy: sync # [overall, sync, optimistic]
