server:
  port: 8003

spring:
  application:
    name: promotion-service # consul 注册中心相关配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 是否注册（默认 true）
        register: true
        # 服务名称
        service-name: ${spring.application.name}
        # 展示实例 ip（默认 false）
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promotion-service
    username: root
    password: 123456
  flyway:
    baseline-on-migrate: true
    enabled: true
  redis:
    database: 0
    #    host: redis
    #    port: 6379
    # 连接超时时间
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 1000 # 连接池最大连接数（负值表示无限制）
        max-wait: -1 # 连接池最大阻塞等待时间
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 10 # 连接池最小空闲连接
    cluster:
      nodes:
        - localhost:6379
        - localhost:6380
        - localhost:6381
        - localhost:6382
        - localhost:6383
        - localhost:6384
  session:
    store-type: none

logging:
  file:
    name: logs/PromotionApp.log  # 日志文件路径和名称
    level:
      root: info  # 默认日志级别
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Config
promotion:
  stock-strategy: optimisticBatis # [overall, sync, optimisticJooq, optimisticBatis]