server:
  port: 8090

spring:
  application:
    name: gateway-service # consul 注册中心相关配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: # 是否注册（默认 true）
        register: true
        # 服务名称
        service-name: ${spring.application.name}
        # 展示实例 ip（默认 false）
        prefer-ip-address: true
    gateway:
      globalcors:
        # 支持浏览器 CORS preflight options 请求
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 86400
      discovery:
        locator:
          enabled: true # 开启从注册中心动态路由，使用注册中心的微服务进行路由
          lower-case-service-id: true
      routes:
        - id: account-route
          # uri: http://localhost:8001
          uri: lb://user-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=0
        - id: commodity-route
          uri: lb://commodity-service
          predicates:
            - Path=/commodity/**
          filters:
            - StripPrefix=0
        - id: system-route
          uri: lb://user-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=0
        - id: promotion-route
          uri: lb://promotion-service
          predicates:
            - Path=/promotion/**
          filters:
            - StripPrefix=0
        - id: order-route-1
          uri: lb://order-service-1
          predicates:
            - Path=/order/**
#            - Header=mark, 1
          filters:
            - StripPrefix=0
#        - id: order-route-2
#          uri: lb://order-service-2
#          predicates:
#            - Path=/order/**
#            - Header=mark, 2
#          filters:
#            - StripPrefix=0
