/*
 * This file is generated by jOOQ.
 */
package com.skillup.infrastructure.jooq;


import com.skillup.infrastructure.jooq.tables.Order;


/**
 * Convenience access to all tables in order-service-2.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>order-service-2.order</code>.
     */
    public static final Order ORDER = Order.ORDER;
}
